"""Experimental, host-confirmed durable memory ledger.

The ledger is intentionally opt-in and does not alter the legacy vector store,
profiles, sessions, or :class:`protoprompt.MemoryService`. Import it directly
from ``protoprompt.ledger``. The experimental ``protoprompt.ledger.recall``
package remains separate by default; its explicit host-owned composer can form
one admitted Ledger data lane in a bounded request without auto-wiring legacy
memory or reference applications.
"""

from protoprompt.ledger.sqlite import SqliteMemoryLedger
from protoprompt.ledger.postgres import PostgresMemoryLedger
from protoprompt.ledger.admission import (
    MemoryAdmissionDecision,
    MemoryAdmissionError,
    MemoryAdmissionPolicy,
    MemoryAdmissionPolicyError,
    MemoryReview,
    MemoryReviewGate,
    StaleMemoryReviewError,
)
from protoprompt.ledger.policy import (
    MEMORY_POLICY_SCHEMA_VERSION,
    MemoryPolicy,
    MemoryPolicyError,
)
from protoprompt.ledger.storage_conformance import (
    LEDGER_STORAGE_CAPABILITIES_SCHEMA_VERSION,
    LEDGER_STORAGE_CONTRACT_ID,
    LEDGER_STORAGE_CONTRACT_VERSION,
    LEDGER_TARGET_STORAGE_SCHEMA_VERSION,
    STRICT_HOST_LEDGER_SEMANTIC_PROFILE,
    LedgerBackendId,
    LedgerBackupMode,
    LedgerSetupMode,
    LedgerStorageCapabilities,
    LedgerStorageConformanceError,
    postgres_v7_storage_capabilities,
    sqlite_v7_storage_capabilities,
)
from protoprompt.ledger.types import (
    ErasureReceipt,
    LedgerConflictError,
    LedgerError,
    LedgerNotReadyError,
    LedgerStateError,
    MemoryAdmissionAction,
    MemoryAdmissionAudit,
    MemoryEvent,
    MemoryEventType,
    MemoryKind,
    MemoryOrigin,
    MemoryRecord,
    MemoryRelation,
    MemoryRelationType,
    MemoryState,
    MemoryTrust,
    SCOPE_PAYLOAD_PURGE_SCHEMA_VERSION,
    ScopePayloadPurgeReceipt,
    ScopePayloadReadback,
)
from protoprompt.ledger.writer import MemoryWriter
from protoprompt.ledger.task_resume import (
    MAX_TASK_COMPLETED_ACTION_COUNT,
    TASK_EPISODE_REFERENCE_SCHEMA_VERSION,
    TASK_EPISODE_REFERENCE_TYPE,
    TASK_RESUME_SCHEMA_VERSION,
    TaskEpisode,
    TaskEpisodeReference,
    TaskEpisodeReferenceError,
    TaskOutcome,
    TaskProcedure,
    TaskResumePayload,
    TaskResumePayloadError,
    decode_task_episode_reference,
    decode_task_resume_payload,
    encode_task_episode_reference,
    encode_task_resume_payload,
    project_task_episode_reference,
)
from protoprompt.ledger.task_resume_planner import (
    TASK_RESUME_ADAPTER_SCHEMA_VERSION,
    TASK_RESUME_REFERENCE_REQUEST_SCHEMA_VERSION,
    TASK_RESUME_SCOPE_KIND,
    TaskResumeBindingError,
    TaskResumeConfigurationError,
    TaskResumeError,
    TaskResumePayloadBindingError,
    TaskResumePlanner,
    TaskResumeReferenceRequest,
    TaskResumeSelectionError,
    task_resume_scope,
)

__all__ = [
    "ErasureReceipt",
    "LedgerConflictError",
    "LedgerError",
    "LedgerNotReadyError",
    "LedgerStateError",
    "LEDGER_STORAGE_CAPABILITIES_SCHEMA_VERSION",
    "LEDGER_STORAGE_CONTRACT_ID",
    "LEDGER_STORAGE_CONTRACT_VERSION",
    "LEDGER_TARGET_STORAGE_SCHEMA_VERSION",
    "MemoryAdmissionAction",
    "MemoryAdmissionAudit",
    "MemoryAdmissionDecision",
    "MemoryAdmissionError",
    "MemoryAdmissionPolicy",
    "MemoryAdmissionPolicyError",
    "MEMORY_POLICY_SCHEMA_VERSION",
    "MemoryEvent",
    "MemoryEventType",
    "MemoryKind",
    "MemoryOrigin",
    "MemoryPolicy",
    "MemoryPolicyError",
    "MemoryRecord",
    "MemoryRelation",
    "MemoryRelationType",
    "MemoryState",
    "MemoryTrust",
    "MemoryReview",
    "MemoryReviewGate",
    "MemoryWriter",
    "MAX_TASK_COMPLETED_ACTION_COUNT",
    "PostgresMemoryLedger",
    "LedgerBackendId",
    "LedgerBackupMode",
    "LedgerSetupMode",
    "LedgerStorageCapabilities",
    "LedgerStorageConformanceError",
    "SqliteMemoryLedger",
    "SCOPE_PAYLOAD_PURGE_SCHEMA_VERSION",
    "ScopePayloadPurgeReceipt",
    "ScopePayloadReadback",
    "StaleMemoryReviewError",
    "STRICT_HOST_LEDGER_SEMANTIC_PROFILE",
    "TASK_EPISODE_REFERENCE_SCHEMA_VERSION",
    "TASK_EPISODE_REFERENCE_TYPE",
    "TASK_RESUME_ADAPTER_SCHEMA_VERSION",
    "TASK_RESUME_REFERENCE_REQUEST_SCHEMA_VERSION",
    "TASK_RESUME_SCHEMA_VERSION",
    "TASK_RESUME_SCOPE_KIND",
    "TaskEpisode",
    "TaskEpisodeReference",
    "TaskEpisodeReferenceError",
    "TaskOutcome",
    "TaskProcedure",
    "TaskResumeBindingError",
    "TaskResumeConfigurationError",
    "TaskResumeError",
    "TaskResumePayload",
    "TaskResumePayloadBindingError",
    "TaskResumePayloadError",
    "TaskResumePlanner",
    "TaskResumeReferenceRequest",
    "TaskResumeSelectionError",
    "decode_task_episode_reference",
    "decode_task_resume_payload",
    "encode_task_episode_reference",
    "encode_task_resume_payload",
    "project_task_episode_reference",
    "postgres_v7_storage_capabilities",
    "sqlite_v7_storage_capabilities",
    "task_resume_scope",
]
